global:
  image:
    # registry: &imageRegistry "localregistry.machina-mgmt-prod.space:5000/docker"
    registry: &imageRegistry "docker.io"

alloy:
  clustering:
    # -- Deploy Alloy in a cluster to allow for load distribution.
    enabled: true
  mounts:
    # -- Mount /var/log from the host into the container for log collection.
    varlog: true
    # -- Mount /var/lib/docker/containers from the host into the container for log
    # collection.
    dockercontainers: true
  enableReporting: false
  resources:
    requests:
      cpu: "0.5"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi

image:
  registry: *imageRegistry
  repository: grafana/alloy
  tag: v1.5.0


configReloader:
  # -- Enables automatically reloading when the Alloy config changes.
  enabled: false
  image:
    registry: registry1.dso.mil
    repository: ironbank/opensource/jimmidyson/configmap-reload
    tag: v0.13.1

serviceMonitor:
  enabled: false

controller:
  tolerations:
    - key: cpu
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: CriticalAddonsOnly
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
