{{- $values := (mustMergeOverwrite .Values.alloy (or .Values.agent dict)) -}}
{{- if $values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alloy.fullname" . }}-config
  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  config.alloy: |-
    logging {
      level  = "debug"
      format = "logfmt"
    }
    {{- range $values.configMap.files }}
    import.file "{{ . | trimSuffix ".alloy" }}" {
        filename = "/etc/alloy/{{ . }}"
    }
    {{- end }}
    {{- if $values.configMap.config }}
    // Base configuration
    {{ $values.configMap.config | nindent 4 }}
    {{- end }}
    // Prometheus configuration
    {{ include "alloy.prometheusRemoteConfig" . | nindent 4 }}
    // Loki remote config
    {{ include "alloy.lokiRemoteConfig" . | nindent 4 }}
{{- end }}